[package]
name = "meu-fbe-tez"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Hakan GÜLEN <https://github.com/hkngln>"]
license = "MIT"
repository = "https://github.com/hkngln/meu-fbe-tez"
description = "Mersin Üniversitesi Fen Bilimleri Enstitüsü yüksek lisans / doktora tez şablonu."
keywords = ["thesis", "tez", "mersin", "turkish"]
categories = ["thesis"]
compiler = "0.15.0"
exclude = ["tests", "docs", ".github", "CONTRIBUTING.md"]

[template]
path = "template"
entrypoint = "main.typ"
